# Site
name: 'Artur Araripe'
description: 'Boring content creator from Brazil that loves emulators, airplanes and virtual machines'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'arturararipe@protonmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    ara:
      name:           Ara
      site:           https://www.arturararipe.nl
      avatar:         assets/images/avatar1.jpg
      bio:            "A 24 year old Social Communicator that loves writing about games (mainly simulators), somewhat into music and IT, even more so if it’s hypervisor stuff or old x86 emulators, which explains the randomness of this blog. I also have a YouTube channel which is very much like this blog when it comes to how random it is: from your average game benchmark to tutorials on how to install UNIX System V"
      email:          arturararipe@protonmail.com
      twitter:        https://twitter.com/arturararipe

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: ara
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]